spring:
  application:
    name: oqrs-service
  datasource:
    url: jdbc:h2:mem:mydb
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

jwt:
  secret: dZO4m9GNCwtHGJ5nOoBbWDETDVa34343xxXFerv$^223!$#@%$^*!